### PR TITLE
Updates the version of weave-net to 2.7.0

### PR DESCRIPTION
**Pull request by palemtnrider**
WKP-1012. Update to the latest released version of weave-net

### CODE REVIEW

**Comment by jrryjcksn** [comment]
So... I'm guessing the cpu and readonly changes were from the release notes?

**Comment by palemtnrider** [comment]
> So... I'm guessing the cpu and readonly changes were from the release notes?

I pulled the latest version of weave-net from weave cloud and those changes were included in it.

**Comment by bboreham** [comment]
The config from Weave Cloud is [awaiting a fix for those requests](https://github.com/weaveworks/launch-generator/pull/398)
Suggest you use https://github.com/weaveworks/weave/releases/download/latest_release/weave-daemonset-k8s-1.11.yaml

The fixed numbers are a gamble because you need more as your cluster grows; reducing them is a big risk.

**Comment by bboreham** [comment]
Weave Net 2.7.0 has been released.

**Comment by palemtnrider** [comment]
I'll update the PR to the 2.7.0 release.

**Comment by palemtnrider** [comment]
> The fixed numbers are a gamble because you need more as your cluster grows; reducing them is a big risk.

I'll revert this part of the change as well.

**Comment by bboreham** [comment]
Should have been made on master then cherry-picked.

**Pull request merged**
