### PR TITLE
add initial rtd support

### PR DESCRIPTION
**Pull request by dholbach**
Following up on the discussion with @dimitropoulos from #46 ... I just went ahead and created a draft PR with the initial bits for `wksctl` docs in readthedocs.io - let me know what you think.

### CODE REVIEW

**Comment by dholbach** [comment]
Adding the linkcheck unveiled https://circleci.com/gh/weaveworks/wksctl/1015 - fixed in 7753c9a8c254566e15396439e361c1252ae7780f

**Comment by dholbach** [comment]
Err... 244e100.

**Comment by dholbach** [comment]
Missing:

- [ ] change links in main README.md
- [ ] set up `wksctl.readthedocs.io` with our bot account
- [ ] figure out why "make push" in CI fails
- [ ] :champagne: ?

**Comment by dholbach** [comment]
To play around with this, check out this branch, run

```
make serve-docs
```

Head to `http://localhost:8000/_build/html/index.html`.

**Comment by dholbach** [comment]
Screenshot from 2019-09-17 15-17-10

**Comment by dimitropoulos** [comment]
@dholbach could you please add me: my rtd username is `dimitropoulos`?

**Pull request merged**
