### PR TITLE
ignore *_vfsdata.go

### PR DESCRIPTION
**Pull request by saada**
In wksctl project, why dont we git ignore the manifests_vfsdata.go file?
What value does it add if any? 

I found it cumbersome and allowed for several rebase related bugs where it wouldn’t compile the most up to date files at build time. Or in other cases it would throw errors if I didn’t update any local file

### CODE REVIEW

**Comment by saada** [comment]
Counter argument: http://github.com/weaveworks/wksctl/pull/51

**Comment by saada** [comment]
https://en.wikipedia.org/wiki/Wikipedia:Chesterton%27s_fence

**Comment by mflendrich** [comment]
> Counter argument: [http://github.com/weaveworks/wksctl/pull/51](https://github.com/weaveworks/wksctl/pull/51)

Exactly, this is the reason for the generated files being committed in :).

Below is an authoritative statement (by one of the golang maintainers) that `go generate` shall be executed on the module author's side (here: wksctl), and not on the module user's side (which I interpret, by extension, as anyone who `git clone`s):
> note that generate is intended to be run by the author of the module, not its users

source:  https://github.com/golang/go/issues/25922#issuecomment-398558712

> I found it cumbersome and allowed for several rebase related bugs where it wouldn’t compile the most up to date files at build time. Or in other cases it would throw errors if I didn’t update any local file

Could you describe the build bugs you're facing? I might be able to help. Probably it's a matter of a missing `go generate` step somewhere in the makefile execution path you're bumping into.

**Comment by saada** [comment]
Mostly rebases. I tend to have to manually change a file for go generate to work.
I'm happy to close this PR if there's a solution to that.

**Comment by mflendrich** [comment]
@saada Most probably, the source of the problem is in the `Makefile`.

`make` decides whether to `go generate` (precisely speaking - to build a [target that has `go generate` in its recipe](https://github.com/weaveworks/wksctl/blob/660e789ffcccea1a5b2267e3d2ca0af7889b8fb2/Makefile#L72)) when at least one of its dependencies is newer than the target file (or if the target file doesn't exist). From your problem description, it seems that `make` does not check some required file for modification when it decides to build such a target or not.

For the problematic autogenerated file, ensure that all its dependencies are properly listed in its target's dependencies. Probably something is missing - maybe the `.go` file containing the `go:generate` directive itself.

**Comment by saada** [comment]
Could it be that rebase file changes don't update modified timestamp? and hence go generate doesn't know the contents changed?

**Comment by mflendrich** [comment]
> 
> 
> Could it be that rebase file changes don't update modified timestamp? and hence go generate doesn't know the contents changed?

No. See the [official FAQ entry](https://git.wiki.kernel.org/index.php/Git_FAQ#Why_isn.27t_Git_preserving_modification_time_on_files.3F).

**Comment by mflendrich** [comment]
> and hence go generate doesn't know the contents changed?

Also note that it's `make`, not `go generate`, that cares about timestamps.

**Comment by bboreham** [comment]
New idea: #261

**Pull request closed without merging**
