### PR TITLE
Fix helm ops version

### PR DESCRIPTION
**Pull request by chanwit**
This PR fixes the Helm Ops namespace and downgrade Helm Ops to be compatible with EKS.

### CODE REVIEW

**Comment by palemtnrider** [comment]
The code changes LGTM.  

@chanwit can you elaborate on how you tested this?  When I added
```
+      addons:
+      - name: flux-helm-op
```
to a cluster.yaml file, I recieved 
```
C9D341A6-0000-0000-AC12-7B29D8998333
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/binHOSTNAME=node0TERM=xtermcontainer=dockerHOME=/rootError: failed to set up seed node (127.0.0.1): unable to update namespace: Unable to decode item's raw field: no kind "CustomResourceDefinition" is registered for version "apiextensions.k8s.io/v1beta1" in scheme "pkg/runtime/scheme.go:101"
```
The same thing fails on master.

I suspect I'm using it differently than you are.  Just performing a `wksctl addon build flux-helm-op` works and generates a valid yaml and I can apply it to a cluster built with wksctl.

**Comment by chanwit** [comment]
@palemtnrider I tested it via calling `wks profile enable`.

**Comment by chanwit** [comment]
@palemtnrider here's the command I used to test it:
`
wksctl profile enable \
  --git-url=https://github.com/weaveworks/mlops-profile
`
It will generate manifests into the `base` directory.

**Comment by mflendrich** [comment]
@chanwit have you verified it working all the way up to the helm operator actually working (i.e. deploying HelmReleases)?

**Comment by chanwit** [comment]
yes, verified.

it's been working fine for a large setup like Istio HelmRelease.

**Comment by palemtnrider** [comment]
Hi @chanwit just getting back to this PR - sorry for the delay.  The versions of helm operator and tiller have updated since this PR.  Can you update to operator 1.0 and tiller 2.16.5

**Pull request closed without merging**
