### PR TITLE
v1alpha3 - Rename BareMetal to ExistingInfra

### PR DESCRIPTION
**Pull request by bboreham**
"BareMetal" may make people think we are pxe-booting, while the point of this provider is to take existing machines that run Linux and bring up a Kubernetes node on them.

"ExistingInfra" was one name proposed, so I made this PR to see how it looked.

### CODE REVIEW

**Comment by yiannistri** [comment]
In my opinion, "ExistingInfra" is more precise a term than "BYOB".

**Comment by luxas** [comment]
I prefer this one over the other. Couldn't understand what BYOB was in the first ten seconds I looked at it

**Comment by D3nn** [comment]
> In my opinion, "ExistingInfra" is more precise a term than "BYOB".

I don't know about it in Europe, but  BYOB in the US generally means "Bring Your Own Beer."  Somehow I don't think that's what @yiannistri has in mind.

**Comment by bboreham** [comment]
CI failed; looks like flake #7090

**Comment by twelho** [comment]
@bboreham there's one remaining use of `v1alpha1` in the examples in the [generate-machines-manifest.js](https://github.com/weaveworks/wksctl/blob/existinginfra/examples/gce/generate-machines-manifest.js) script, should I refactor it to `v1alpha3` as well? I don't have a way to test the GCE examples by hand. Are these used/covered by CI?

**Comment by bboreham** [comment]
Thanks for doing the examples, @twelho.  Yes it is best to make everything consistent but I was ok to do it later.

I don't believe any of them are covered by CI.

**Pull request merged**
