### PR TITLE
Refactor test to allow for testing additional OS

### PR DESCRIPTION
**Pull request by yiannistri**
- Refactor test to allow for testing additional OS

### CODE REVIEW

**Comment by bboreham** [comment]
Given we're creating Ubuntu VMs for CI anyway, what is the reasoning to extend a footloose-based test?

**Comment by yiannistri** [comment]
I guess as of now there is some overlap. The original intention was that footloose tests run faster than gcp tests. But I don't feel strongly about keeping them as long as we have coverage.

**Comment by bboreham** [comment]
> faster

That's where I started - two sets of footloose tests appear to be way slower.

**Comment by yiannistri** [comment]
Closing this since we have existing tests.

**Pull request closed without merging**
